version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "jcornaz"
    assignees:
      - "jcornaz"
    ignore:
      - dependency-name: "rapier2d"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "jcornaz"
    assignees:
      - "jcornaz"
