[package]
name = "heron_rapier"
version = "0.1.0-dev"
authors = ["Jonathan Cornaz"]
edition = "2018"

[features]
default = ["3d"]
2d = ["rapier2d"]
3d = ["rapier3d"]

[dependencies]
bevy_math = "^0.4.0"
bevy_ecs = "^0.4.0"
bevy_app = "^0.4.0"
rapier2d = { version = "^0.4.2", optional = true }
rapier3d = { version = "^0.4.2", optional = true }
