[package]
name = "heron_core"
version = "0.1.0-alpha.1"
authors = ["Jonathan Cornaz"]
edition = "2018"
license = "MIT"
description = "Core components and resources to use Heron"
repository = "https://github.com/jcornaz/heron/"

[dependencies]
bevy_math = "^0.4.0"
bevy_ecs = "^0.4.0"

[dev-dependencies]
bevy = { version = "^0.4.0", default-features = false }
